# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_membership_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.DecimalField(decimal_places=55, max_digits=60)),
                ('latitude', models.DecimalField(decimal_places=55, max_digits=60)),
                ('notification_radius', models.IntegerField()),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('started', models.DateField(default=django.utils.timezone.now)),
                ('last', models.DateField(default=events.models.default_last)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
