# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('groups', '0002_membership_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=55, max_digits=60)),
                ('latitude', models.DecimalField(decimal_places=55, max_digits=60)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='events.Event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns_event', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='CreateGroup',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='groups.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns_group', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('activities.activity',),
        ),
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.Activity')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_by', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('activities.activity',),
        ),
    ]
