# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maplocators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locator',
            name='inited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
