# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maplocators', '0002_locator_inited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locator',
            name='inited',
        ),
    ]
