# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Chill'), (2, 'Away'), (3, 'Busy'), (4, 'Hidden'), (5, 'Sleeping')], default=0),
        ),
    ]
