# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faceboookAvatar',
            field=models.CharField(blank=True, default='http://images.hellokids.com/_uploads/_tiny_galerie/20120416/x2t_how-to-draw-a-cute-dinosaur-tutorial-drawing.jpg', max_length=500, null=True),
        ),
    ]
