"""
Django settings for buddymap project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r*p&%&8v-9)^ucji$df)y!8wkn^-ow#0xj38yj3w8wotmb0m!+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','secure-brook-82949.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    #third party apps
    'channels',
    'rest_framework',
    'oauth2_provider',
    'social_django',
    'rest_framework_social_oauth2',

    #our apps
    'friendship',
    'friends',
    'accounts',
    'activities',
    'groups',
    'events',
    'maplocators',
    'buddychat',

    #django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'buddymap.custom_middleware.CustomSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'buddymap.custom_middleware.CustomCsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'buddymap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
}

AUTHENTICATION_BACKENDS = (

    #Facebook
    'social_core.backends.facebook.FacebookAppOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',

    #django rest framework
    'rest_framework_social_oauth2.backends.DjangoOAuth2',

    #django
    'django.contrib.auth.backends.ModelBackend',
)

WSGI_APPLICATION = 'buddymap.wsgi.application'
ASGI_APPLICATION = 'buddymap.routing.application'

#REDIS and Django Channels for Chat
redis_host = os.environ.get('REDIS_URL', 'redis://localhost:6379')
CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation asgi_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [redis_host],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'buddymap',
        'USER': 'buddymap',
        'PASSWORD': '123',
        'PORT': '5432',
        'HOST': 'localhost',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'accounts.social_auth_pipeline.update_user',  # <--- set the path to the function
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
)


######### Buddy Chat Specific Settings ##########
NOTIFY_USERS_ON_ENTER_OR_LEAVE_GROUPS = False

MSG_TYPE_MESSAGE = 0  # For standard messages
MSG_TYPE_WARNING = 1  # For yellow messages
MSG_TYPE_GLOBAL = 2
MSG_TYPE_ALERT = 3  # For red & dangerous alerts
MSG_TYPE_MUTED = 4  # For just OK information that doesn't bother users
MSG_TYPE_ENTER = 5  # For just OK information that doesn't bother users
MSG_TYPE_LEAVE = 6  # For just OK information that doesn't bother users
MSG_TYPE_JOIN = 7  # For just OK information that doesn't bother users

MESSAGE_TYPES_CHOICES = (
    (MSG_TYPE_MESSAGE, 'MESSAGE'),
    (MSG_TYPE_WARNING, 'WARNING'),
    (MSG_TYPE_GLOBAL, 'GLOBAL'),
    (MSG_TYPE_MUTED, 'MUTED'),
    (MSG_TYPE_ENTER, 'ENTER'),
    (MSG_TYPE_LEAVE, 'LEAVE'),
    (MSG_TYPE_JOIN, 'JOIN'),
)

MESSAGE_TYPES_LIST = [
    MSG_TYPE_MESSAGE,
    MSG_TYPE_WARNING,
    MSG_TYPE_GLOBAL,
    MSG_TYPE_MUTED,
    MSG_TYPE_ENTER,
    MSG_TYPE_LEAVE,
    MSG_TYPE_JOIN
]
#########     End Buddy Chat Setting    #########

######### Buddy Locator Specific Settings ##########
NOTIFY_USERS_ON_ENTER_OR_LEAVE_GROUPS = False

LOC_TYPE_MESSAGE = 0  # For standard messages
LOC_TYPE_WARNING = 1  # For yellow messages
LOC_TYPE_GLOBAL = 2
LOC_TYPE_ALERT = 3  # For red & dangerous alerts
LOC_TYPE_MUTED = 4  # For just OK information that doesn't bother users
LOC_TYPE_ENTER = 5  # For just OK information that doesn't bother users
LOC_TYPE_LEAVE = 6  # For just OK information that doesn't bother users
LOC_TYPE_JOIN = 7  # For just OK information that doesn't bother users

MESSAGE_TYPES_CHOICES = (
    (LOC_TYPE_MESSAGE, 'MESSAGE'),
    (LOC_TYPE_WARNING, 'WARNING'),
    (LOC_TYPE_GLOBAL, 'GLOBAL'),
    (LOC_TYPE_MUTED, 'MUTED'),
    (LOC_TYPE_ENTER, 'ENTER'),
    (LOC_TYPE_LEAVE, 'LEAVE'),
    (LOC_TYPE_JOIN, 'JOIN'),
)

MESSAGE_TYPES_LIST = [
    LOC_TYPE_MESSAGE,
    LOC_TYPE_WARNING,
    LOC_TYPE_GLOBAL,
    LOC_TYPE_MUTED,
    LOC_TYPE_ENTER,
    LOC_TYPE_LEAVE,
    LOC_TYPE_JOIN
]
#########     End Buddy Locator Setting    #########


######### Social Authentication Setting #########
# Facebook configuration
SOCIAL_AUTH_FACEBOOK_KEY = '1941676536149627'
SOCIAL_AUTH_FACEBOOK_SECRET = '24098eaec6b6bd1dbea1b7b04b3c6f35'

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email'
}
##################################################

#Overide the existing Authentication User model
AUTH_USER_MODEL = 'accounts.User'
AUTH_PROFILE_MODULE = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = 'https://storage.googleapis.com/buddymap/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'statics')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

USER_IMAGES_DIR = 'user/'
GROUP_IMAGES_DIR = 'group/'

import dj_database_url
db_from_env = dj_database_url.config()
DATABASES['default'].update(db_from_env)

#Custom Session cookie name'
