# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddychat', '0002_auto_20180304_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyroom',
            name='group',
        ),
        migrations.DeleteModel(
            name='BuddyRoom',
        ),
    ]
