# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddychat', '0003_auto_20180304_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddymessage',
            name='message_type',
            field=models.IntegerField(choices=[(0, 'MESSAGE'), (1, 'WARNING'), (2, 'ALERT'), (3, 'MUTED'), (4, 'ENTER'), (5, 'LEAVE')], default=0),
        ),
    ]
