# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddychat', '0004_buddymessage_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddymessage',
            name='message_type',
            field=models.IntegerField(choices=[(0, 'MESSAGE'), (1, 'WARNING'), (2, 'GLOBAL'), (4, 'MUTED'), (5, 'ENTER'), (6, 'LEAVE'), (7, 'JOIN')], default=0),
        ),
    ]
