# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='owner',
            field=models.BooleanField(default=True),
        ),
    ]
